name: train_vrex_defaults_model
display_name: Train VREX Defaults Model
type: command
inputs:
  train_data: 
    type: uri_folder
  test_data: 
    type: uri_folder
  learning_rate:
    type: number     
outputs:
  model:
    type: uri_folder
code: .
environment:
  azureml:train-dependencies:v5
command: >-
  python train.py 
  --train_data ${{inputs.train_data}} 
  --test_data ${{inputs.test_data}} 
  --learning_rate ${{inputs.learning_rate}}
  --model ${{outputs.model}}